# The input field

In [1]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [2]:
import numpy as np

date = [1, 2, 3, 4]
array = np.array(date)
print(array)

[1 2 3 4]


In [3]:
import numpy as np

zeros_array = np.zeros(5)
ones_array = np.ones(5)

print(zeros_array)
print(ones_array)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [6]:
import numpy as np

empty_array = np.empty(3)
range_array = np.arange(5)

print("Empty: " + str(empty_array))
print("Range: " + str(range_array))

Empty: [5.47683936e-310 0.00000000e+000 0.00000000e+000]
Range: [0 1 2 3 4]


In [8]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]
