# Getting Started with Numpy and Arrays

In [1]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [2]:
import numpy as np

date = [1, 2, 3, 4]
array = np.array(date)
print(array)

[1 2 3 4]


In [3]:
import numpy as np

zeros_array = np.zeros(5)
ones_array = np.ones(5)

print(zeros_array)
print(ones_array)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [6]:
import numpy as np

empty_array = np.empty(3)
range_array = np.arange(5)

print("Empty: " + str(empty_array))
print("Range: " + str(range_array))

Empty: [5.47683936e-310 0.00000000e+000 0.00000000e+000]
Range: [0 1 2 3 4]


In [8]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


# Array Data Types and Attributes
ndim: indica il numero di dimensioni dell'array.
shape: una tupla che rappresenta la dimensione di ciascuna dimensione dell'array.
size: il numero totale di elementi all'interno dell'array.
dtype: il tipo di dati degli elementi dell'array.
itemsize: la dimensione in byte di ciascun elemento dell'array.

In [11]:
import numpy as np

int_array = np.array([1, 2, 3, 4], dtype="int32")
float_array = np.array([1.0, 2.0, 3.0], dtype="float64")
print("Array of integers: " + str(int_array))
print("Array of float: " + str(float_array))

Array of integers: [1 2 3 4]
Array of float: [1. 2. 3.]


In [12]:
import numpy as np

date = np.array([[1, 2, 3], [4, 5, 6]], dtype="int64")
print("Number of sizes: ", date.ndim)
print("Array shape: ", date.shape)
print("Total array size: ", date.size)
print("Tipo di dati dell'array: ", date.dtype)
print("Dimensione in byte degli elementi:", date.itemsize, "byte")

Number of sizes:  2
Array shape:  (2, 3)
Total array size:  6
Tipo di dati dell'array:  int64
Dimensione in byte degli elementi: 8 byte
