# Getting Started with Numpy and Arrays

In [1]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [2]:
import numpy as np

date = [1, 2, 3, 4]
array = np.array(date)
print(array)

[1 2 3 4]


In [3]:
import numpy as np

zeros_array = np.zeros(5)
ones_array = np.ones(5)

print(zeros_array)
print(ones_array)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [6]:
import numpy as np

empty_array = np.empty(3)
range_array = np.arange(5)

print("Empty: " + str(empty_array))
print("Range: " + str(range_array))

Empty: [5.47683936e-310 0.00000000e+000 0.00000000e+000]
Range: [0 1 2 3 4]


In [8]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


# Array Data Types and Attributes
ndim: indica il numero di dimensioni dell'array.
shape: una tupla che rappresenta la dimensione di ciascuna dimensione dell'array.
size: il numero totale di elementi all'interno dell'array.
dtype: il tipo di dati degli elementi dell'array.
itemsize: la dimensione in byte di ciascun elemento dell'array.

In [11]:
import numpy as np

int_array = np.array([1, 2, 3, 4], dtype="int32")
float_array = np.array([1.0, 2.0, 3.0], dtype="float64")
print("Array of integers: " + str(int_array))
print("Array of float: " + str(float_array))

Array of integers: [1 2 3 4]
Array of float: [1. 2. 3.]


In [ ]:
import numpy as np

date = np.array([[1, 2, 3], [4, 5, 6]], dtype="int64")
print("Number of sizes: ", date.ndim)
print("Array shape: ", date.shape)
print("Total array size: ", date.size)
print("Tipo di dati dell'array: ", date.dtype)
print("Size of elements in bytes: ", date.itemsize, "byte")

Number of sizes:  2
Array shape:  (2, 3)
Total array size:  6
Tipo di dati dell'array:  int64
Dimensione in byte degli elementi: 8 byte


# Array Indexing and Slicing

In [13]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
first_element = array[0]
fourth_element = array[3]
print("First element: ", first_element)
print("Fourth element: ", fourth_element)

First element:  10
Fourth element:  40


In [14]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

subsequence = array[1:4]
print("Subsequence: ", subsequence)

Subsequence:  [20 30 40]


In [15]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
first_row = matrix[0]
second_row = matrix[:, 1]
print("First row: ", first_row)
print("Second row: ", second_row)

sub_matrix = matrix[0:2, 1:3]
print("Sub_matrix:\n", sub_matrix)

First row:  [1 2 3]
Second row:  [2 5 8]
Sub_matrix:
 [[2 3]
 [5 6]]


In [16]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix[2, 2] = 99
print("Matrix updated:\n", matrix)

Matrix updated:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]]


# Basic operations

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

sum = a + b
sub = a - b
mul = a * b
div = a / b

print("Sum: " + str(sum))
print("Sub: " + str(sub))
print("Mul: " + str(mul))
print("Div: " + str(div))

Sum: [11 22 33 44]
Sub: [ -9 -18 -27 -36]
Mul: [ 10  40  90 160]
Div: [0.1 0.1 0.1 0.1]


In [4]:
import numpy as np

array = np.array([1, 2, 3, 4])

square_roots = np.sqrt(array)
exponential = np.exp(array)

print("Square_roots: " + str(square_roots))
print("Exponential: " + str(exponential))

Square_roots: [1.         1.41421356 1.73205081 2.        ]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]


In [6]:
import numpy as np

c = np.array([1, 2, 3])
d = 10
risult = c + d
print("The result of broadcasting with a scalar:" + str(risult))

x = np.array([1, 2, 3])
y = np.array([[1], [2], [3]])
risult_matrix = x + y
print("The result of broadcasting with a matrix:" + str(risult_matrix))

The result of broadcasting with a scalar:[11 12 13]
The result of broadcasting with a matrix:[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Changing the shape of an array
- ravel: ritorna una vista dell'arrau che puó condividere i dati con l'array originale
- flatten: ritorna una copia

In [8]:
import numpy as np

original_array = np.arange(10)
array_remodeled = original_array.reshape((2, 5))
print("original array: " + str(original_array))
print("original remodeled: " + str(array_remodeled))

original array: [0 1 2 3 4 5 6 7 8 9]
original remodeled: [[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
import numpy as np

array_to_resize = np.array([1, 2, 3, 4])
array_to_resize.resize((2, 3))
print("Array to resize:\n" + str(array_to_resize))

Array to resize:
[[1 2 3]
 [4 0 0]]


In [11]:
import numpy as np

twodimensional_array = np.array([[1, 2], [3, 4]])
flat_ravel = twodimensional_array.ravel()
flat_flatten = twodimensional_array.flatten()
print("Ravel: " + str(flat_ravel))
print("Flatten: " + str(flat_flatten))

Ravel: [1 2 3 4]
Flatten: [1 2 3 4]


# Concatenation and division

In [3]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

concatenate = np.concatenate((array1, array2))
print("Concatenate: " + str(concatenate))

vstack = np.vstack((array1, array2))
print("Vstack:\n" + str(vstack))

hstack = np.hstack((array1, array2))
print("Hstack: " + str(hstack))

Concatenate: [1 2 3 4 5 6]
Vstack:
[[1 2 3]
 [4 5 6]]
Hstack: [1 2 3 4 5 6]


In [4]:
import numpy as np

large_array = np. arange(12)

div = np.split(large_array, 3)
print("divided into 3 parts: ", str(div))

large_matrix = np.array([[1, 2, 3], [4, 5, 6]])
hsplit = np.hsplit(large_matrix, 3)
print("Hsplit:\n" + str(hsplit))

divided into 3 parts:  [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
Hsplit:
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


# Broadcasting Operations

In [7]:
import numpy as np

array = np.array([1, 2, 3])
number = 4
risult = array + number
print("Risult: " + str(risult))

Risult: [5 6 7]


In [8]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([100, 200, 300])

z = x + y
print("z: " + str(z))

z: [[101 202 303]
 [104 205 306]]


In [9]:
import numpy as np

dataset = np.random.randint(0, 100, size=(5, 3))
average = dataset.mean(axis=0)
standard_waste = dataset.std(axis=0)

normalized_dataset = (dataset - average) / standard_waste

print("Original dataset:\n" + str(dataset))
print("Normalized dataset:\n" + str(normalized_dataset))

Original dataset:
[[68 40 90]
 [69 71  4]
 [30 74 40]
 [54 11 31]
 [89 44 64]]
Normalized dataset:
[[ 0.30763164 -0.34723583  1.50987848]
 [ 0.35890358  0.99830301 -1.42789412]
 [-1.64070206  1.12851644 -0.19812885]
 [-0.41017552 -1.60596571 -0.50557017]
 [ 1.38434237 -0.17361791  0.62171467]]


# Basic statistical functions

In [12]:
import numpy as np

date = np.array([10, 20, 30, 40, 50])

print("Average: " + str(np.mean(date)))
print("Median: " + str(np.median(date)))
print("standard deviation: " + str(np.std(date)))
print("Variance: " + str(np.var(date)))

Average: 30.0
Median: 30.0
standard deviation: 14.142135623730951
Variance: 200.0


In [15]:
import numpy as np

date = np.array([10, 20, 30, 40, 50])

print("standard deviation (sample): " + str(np.std(date, ddof=1)))
print("Variance (sample): " + str(np.var(date, ddof=1)))

print("Minimum: " + str(np.min(date)) + " maximum: " + str(np.max(date)))
print("Grand total: " + str(sum(date)) + " Total product: " + str(np.prod(date)))

standard deviation (sample): 15.811388300841896
Variance (sample): 250.0
Minimum: 10 maximum: 50
Grand total: 150 Total product: 12000000
